In [2]:
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline 
import seaborn as sns 
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import LabelEncoder 
from sklearn.preprocessing import MinMaxScaler 
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.ensemble import RandomForestRegressor 
from sklearn.metrics import mean_squared_error

In [3]:
import pandas as pd
# 데이터 불러오기
df = pd.read_excel("accident_stat.xlsx")

In [6]:
df

   사고유형대분류     사고유형중분류        사고유형   사고건수  사망자수   중상자수   경상자수  부상신고자수
0     차대사람         횡단중         횡단중  12767   445   5999   6664     458
1     차대사람       차도통행중       차도통행중   3628   146   1438   2007     183
2     차대사람  길가장자리구역통행중  길가장자리구역통행중   1973    33    563   1330     121
3     차대사람       보도통행중       보도통행중   2226    21    745   1455     131
4     차대사람          기타          기타  14675   333   4887   9139    1062
5      차대차        정면충돌        정면충돌   7892   205   3539   8837     588
6      차대차        측면충돌        측면충돌  71687   404  17756  84667    5781
7      차대차       후진중충돌       후진중충돌   3514     2    304   4172     162
8      차대차          추돌          추돌  32717   379   7564  47111    2748
9      차대차          기타          기타  44222   248   9990  49616    3839
10    차량단독          전도          전도    956    82    384    403     209
11    차량단독          전복          전복    165    36     87     81      27
12    차량단독       공작물충돌       공작물충돌   2742   340   1256   1504     532
13    차량단독   주/정차차량 충돌   주/정차차량 충돌     23     3      7      8       6
14    차량단독        도로이탈     도로이탈 추락    385    73    199    179      44
15    차량단독        도로이탈     도로이탈 기타    156    18     73     79      34
16    차량단독          기타          기타   3401   148   1114   2030     495

In [9]:
# 사고유형중분휴에 따른 사망자수 합
df.groupby("사고유형중분류")["사망자수"].sum()

사고유형중분류
공작물충돌         340
기타            729
길가장자리구역통행중     33
도로이탈           91
보도통행중          21
전도             82
전복             36
정면충돌          205
주/정차차량 충돌       3
차도통행중         146
추돌            379
측면충돌          404
횡단중           445
후진중충돌           2
Name: 사망자수, dtype: int64